import { randomUUID } from "node:crypto";
import { asc, eq } from "drizzle-orm";
import type { PointGuideDatabase } from "@/db/client";
import { auditEvents, sourceChunks, sourceRepositories } from "@/db/schema";
import { SourceStoreError } from "@/lib/sources/store";
import type { SourceRepositoryRecord, SourceRepositoryStore, ValidatedSource } from "@/lib/sources/types";

function fromRow(row: typeof sourceRepositories.$inferSelect): SourceRepositoryRecord { return { id: row.id, fullName: row.fullName, url: row.url, status: row.status as SourceRepositoryRecord["status"], defaultBranch: row.defaultBranch, indexedCommit: row.indexedCommit, validationReport: row.validationReport as unknown as SourceRepositoryRecord["validationReport"], linkedAt: row.linkedAt.toISOString(), updatedAt: row.updatedAt.toISOString(), version: row.version }; }
export class PostgresSourceRepositoryStore implements SourceRepositoryStore {
  constructor(private readonly database: PointGuideDatabase, private readonly builtinCommit?: string) {}
  private async syncBuiltin() { if (!this.builtinCommit) return; const [current] = await this.database.select().from(sourceRepositories).where(eq(sourceRepositories.fullName, "PointCommunity/pointaudio")).limit(1); if (current?.indexedCommit === "configured-at-runtime") { const report = { ...(current.validationReport as Readonly<Record<string, unknown>>), commitSha: this.builtinCommit, checkedAt: new Date().toISOString() }; await this.database.update(sourceRepositories).set({ indexedCommit: this.builtinCommit, validationReport: report, updatedAt: new Date(), version: current.version + 1 }).where(eq(sourceRepositories.id, current.id)); } }
  async list() { await this.syncBuiltin(); return (await this.database.select().from(sourceRepositories).orderBy(asc(sourceRepositories.fullName))).map(fromRow); }
  async link(actorId: string, source: ValidatedSource) { const existing = await this.database.select({ id: sourceRepositories.id }).from(sourceRepositories).where(eq(sourceRepositories.fullName, source.fullName)).limit(1); if (existing.length) throw new SourceStoreError("SOURCE_EXISTS", "That repository is already linked."); return this.database.transaction(async (transaction) => { const now = new Date(); const id = randomUUID(); const [row] = await transaction.insert(sourceRepositories).values({ id, fullName: source.fullName, url: source.url, status: "ACTIVE", defaultBranch: source.report.defaultBranch, indexedCommit: source.report.commitSha, validationReport: source.report as unknown as Readonly<Record<string, unknown>>, linkedBy: actorId, linkedAt: now, updatedAt: now, version: 1 }).returning(); if (!row) throw new Error("Source insert failed."); if (source.chunks.length) await transaction.insert(sourceChunks).values(source.chunks.map((chunk) => ({ repositoryId: id, chunkId: chunk.chunkId, sourceId: chunk.sourceId, title: chunk.title, path: chunk.path, locator: chunk.locator, authority: chunk.authority, capturedAt: new Date(chunk.capturedAt), digest: chunk.digest, content: chunk.text }))); await transaction.insert(auditEvents).values({ id: randomUUID(), actorId, action: "source_repository.linked", targetType: "source_repository", targetId: id, outcome: "SUCCEEDED", metadata: { fullName: source.fullName, commit: source.report.commitSha, chunks: source.chunks.length }, occurredAt: now }); return fromRow(row); }); }
  private async required(id: string) { const [row] = await this.database.select().from(sourceRepositories).where(eq(sourceRepositories.id, id)).limit(1); if (!row) throw new SourceStoreError("SOURCE_NOT_FOUND", "Source repository was not found."); return row; }
  async archive(actorId: string, id: string, confirmation: string) { const current = await this.required(id); if (confirmation !== current.fullName) throw new SourceStoreError("CONFIRMATION_REQUIRED", `Type ${current.fullName} to confirm archival.`); return this.database.transaction(async (transaction) => { const now = new Date(); const [row] = await transaction.update(sourceRepositories).set({ status: "ARCHIVED", updatedAt: now, version: current.version + 1 }).where(eq(sourceRepositories.id, id)).returning(); await transaction.insert(auditEvents).values({ id: randomUUID(), actorId, action: "source_repository.archived", targetType: "source_repository", targetId: id, outcome: "SUCCEEDED", metadata: { fullName: current.fullName }, occurredAt: now }); return fromRow(row!); }); }
  async remove(actorId: string, id: string, confirmation: string) { const current = await this.required(id); if (current.status !== "ARCHIVED") throw new SourceStoreError("ARCHIVE_REQUIRED", "Archive the repository before deleting it."); if (confirmation !== current.fullName) throw new SourceStoreError("CONFIRMATION_REQUIRED", `Type ${current.fullName} to confirm deletion.`); await this.database.transaction(async (transaction) => { const now = new Date(); await transaction.delete(sourceRepositories).where(eq(sourceRepositories.id, id)); await transaction.insert(auditEvents).values({ id: randomUUID(), actorId, action: "source_repository.deleted", targetType: "source_repository", targetId: id, outcome: "SUCCEEDED", metadata: { fullName: current.fullName }, occurredAt: now }); }); }
  async activeChunks() { await this.syncBuiltin(); const rows = await this.database.select({ chunk: sourceChunks }).from(sourceChunks).innerJoin(sourceRepositories, eq(sourceChunks.repositoryId, sourceRepositories.id)).where(eq(sourceRepositories.status, "ACTIVE")); return rows.map(({ chunk }) => ({ chunkId: chunk.chunkId, sourceId: chunk.sourceId, title: chunk.title, path: chunk.path, locator: chunk.locator, authority: chunk.authority, capturedAt: chunk.capturedAt.toISOString(), digest: chunk.digest, text: chunk.content })); }
}
